### ISSUE TITLE
-inProcess Try ?

### ISSUE THREAD

**Issue by klaussa** [TimNZ/nightmare#1]
Hi,

I've been trying to test the code for the inProcess flag for Nightmare but for some reason it doesn't work :( in my setup. The webpack keeps giving me  
```
Module parse failed: Unexpected token m in JSON at position 0
[0] You may need an appropriate loader to handle this file type. 
``` 
I have added a json-loader. But it just won't work :( Not sure why. 

Also, do I need to compile the files in anyway ?
K

**Comment by TimNZ** [comment]
I got no idea what's causing the webpack error.

The enhancements are definitely still a WIP, but I've not worked 
on this for a while, and no idea if/when I will resume as the project driving
it is on hold.

**Comment by klaussa** [comment]
Hi,

Totally agreed, Is it at least something that was usable / working at any point ? I would be more than happy to pursue, I got a webview and a renderrer as following:

Index.html:
```
<webview style=“height:600px; border:1px solid red” src="https://www.google.com"nodeintegeration></webview>


<script>
require('./renderer.js');
</script>

```
and Renderer.js:

```
    var Nightmare = require('../nightmare/nightmare.js')
    
    let webview = document.querySelector('webview')
     
    webview.addEventListener("dom-ready", function(){
   
      var nightmare = new Nightmare({
            inProcess: {
                window: webview
            }
            
        });
   
       setTimeout(() => {
             console.log(nightmare)

              nightmare
                .goto('https://www.facebook.com/')
                  .type('input[name="q"]','github')
                  .click('input[name="btnK"]')
                  .wait('#ires')
            }, 5000)



    });
```

Does it look like I am doing something wrong ?
Nightmare is present in the console log as following:

![screen shot 2018-05-10 at 02 37 11](https://user-images.githubusercontent.com/1549623/39847742-123416ba-53fb-11e8-9f67-3fd6fcbf19ad.png)

Not sure why is not working, the page stays on google :( 
@TimNZ

**Comment by TimNZ** [comment]
It was definitely working.

When I paused it, I was digging deep into simultaneous in-process execution issues.
At the time it was Electron 1.8.x, and I discovered a bug in Electron with IPC messages from renderer->browser->renderer getting lost

Maybe that got resolved with 2.0

**Comment by klaussa** [comment]
Alright,

I am committed to work with a colleague on pursuing this further. Would you please be able to advise / review our path ? 

At the same time, do you have any idea what could possibly be that it doesn't work in the implementation above ? Running the electron with the debugging flag for nightmare I can see nightmare starting and outputting this:

![screen shot 2018-05-10 at 16 06 11](https://user-images.githubusercontent.com/1549623/39876826-1c2d7f78-546c-11e8-88f2-174bf97be7a2.png)

But the webview is still on the initial URL ( google )

Update1:

Okay I took every ticket I could find on nightmare, and at some point I found that someone had something similar. The solution was to add a .then.

```
   setTimeout(() => {
             //console.log(nightmare)

              nightmare
                .goto('https://www.facebook.com/')
                .then(()=>{ console.log('ready action')}) <- this makes the view to change.

       }, 2000)

``` 
Using this makes it work. Hopefully this would add a hint ? What can it be ?

Kind Regards

**Comment by TimNZ** [comment]
I can look at this next week.

**Comment by klaussa** [comment]
**Update 2**:

Another Problem is that it won't click on anything or type or click.  
Also do you have any idea why there are 2 folders inside the nightmare module ( installed via npm ) but only one in the official repo ?  I have looked through and the differences between them is quite significant ( src vs lib folder ).

**Comment by klaussa** [comment]
**Update3:**

After 6hours of debugging I have found out that after navigating ( webview changing visually to the new url, the boolean in runner-instance at line 220:

```
console.log('DOES IT MATCH?', webContents.getURL(), url);
      if (webContents.getURL() == url) {

```
Still shows 

![screen shot 2018-05-11 at 05 30 48](https://user-images.githubusercontent.com/1549623/39906772-b46dc20a-54dc-11e8-8c67-e67957940b6d.png)

Basically the default URL of the web view its github and even after I see the change in electron's webview as changing the page but in this context it is still not changed. I am close to reaching my digging capabilities due to lack of architectural knowledge on electron :(.

@TimNZ What's your opinion ?

To recap, the URL incoming from respond is good. The   webContents.getURL() is still showing as OLD. Might it be something that might not have been updated somewhere ? 

K

**Comment by klaussa** [comment]
**Update 4:**

Taking the URL with win.getWebContents().getURL() instead of win.getURL() produces:

![screen shot 2018-05-11 at 05 47 50](https://user-images.githubusercontent.com/1549623/39907194-f9ed0aaa-54de-11e8-9ed8-58b07b53925a.png)

I presume some simple sanitising is required.
But still not going to the next operation in the queue :( 
The Done function upon a console log shows: 

```
function (err) {
      err = serializeError(err);
      emitter.emit.apply(emitter, [`CALL_RESULT_${id}`].concat(err).concat(sliced(arguments, 1)));
    }

```

**Comment by klaussa** [comment]
Hei . @TimNZ ,

I got a bit stuck. 
I tried running your implementation leaving aside the web view element and going into the idea of using browser windows. Still the browser window is spawned but is just plain white and the dev console says its disconnected. 

So far I have took every line of your implementation and compared with the original one in order to understand the differences. I don't get what initFn does :(. Also I don't get the communication that uses the webview ?
